<?php
/**
 * @var viewModel $helper
 * @var int $cartCount
 * @var float $totalPrice
 * @var \Zend\View\Model\ViewModel $cartView
 */
?>
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>E-Commerce - MDBootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="/mamaz/public/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
<!--    <link href="../css/materialize.min.css" rel="stylesheet">-->
    <!-- Material Design Bootstrap -->
    <link href="/mamaz/public/css/mdb.min.css" rel="stylesheet">

</head>

<body class="product-v1 hidden-sn white-skin animated">

<!-- Navigation -->
<header>

    <!-- Sidebar navigation -->
    <ul id="slide-out" class="side-nav custom-scrollbar">

        <!-- Logo -->
        <li>

            <div class="logo-wrapper waves-light">

                <a href="#">

                    <img src="/mamaz/public/img/Mama_Zs_African_Supermarket_Restaurant_Oklahoma_City.OK.png" class="img-fluid flex-center">

                </a>

            </div>

        </li>
        <!-- Logo -->

        <!-- Search Form -->
        <li>

            <form class="search-form" role="search">

                <div class="form-group md-form mt-0 pt-1 waves-light">

                    <input type="text" class="form-control" placeholder="Search">

                </div>

            </form>

        </li>
        <!-- Search Form -->

        <!-- Side navigation links -->
        <li>

            <ul class="collapsible collapsible-accordion">

                <li>

                    <a class="collapsible-header waves-effect arrow-r">

                        <i class="fas fa-shopping-cart"></i> Cart page

                        <i class="fas fa-angle-down rotate-icon"></i>

                    </a>

                    <div class="collapsible-body">

                        <ul>

                            <li>

                                <a href="../cart/cart-v1.html" class="waves-effect">Cart V.1</a>

                            </li>

                            <li>

                                <a href="../cart/cart-v2.html" class="waves-effect">Cart V.2</a>

                            </li>

                        </ul>

                    </div>

                </li>

                <li>

                    <a class="collapsible-header waves-effect arrow-r">

                        <i class="far fa-hand-pointer"></i> Category page

                        <i class="fas fa-angle-down rotate-icon"></i>

                    </a>

                    <div class="collapsible-body">

                        <ul>

                            <li>

                                <a href="../category/category-v1.html" class="waves-effect">Category V.1</a>

                            </li>

                            <li>

                                <a href="../category/category-v2.html" class="waves-effect">Category V.2</a>

                            </li>

                            <li>

                                <a href="../category/category-v3.html" class="waves-effect">Category V.3</a>

                            </li>

                            <li>

                                <a href="../category/category-v4.html" class="waves-effect">Category V.4</a>

                            </li>

                        </ul>

                    </div>

                </li>

                <li>

                    <a class="collapsible-header waves-effect arrow-r">

                        <i class="far fa-bookmark"></i> Homepage

                        <i class="fas fa-angle-down rotate-icon"></i>

                    </a>

                    <div class="collapsible-body">

                        <ul>

                            <li>

                                <a href="../homepage/homepage-v1.html" class="waves-effect">Homepage V.1</a>

                            </li>

                            <li>

                                <a href="../homepage/homepage-v2.html" class="waves-effect">Homepage V.2</a>

                            </li>

                            <li>

                                <a href="../homepage/homepage-v3.html" class="waves-effect">Homepage V.3</a>

                            </li>

                        </ul>

                    </div>

                </li>

                <li>

                    <a class="collapsible-header waves-effect arrow-r">

                        <i class="fas fa-camera-retro"></i> Product page

                        <i class="fas fa-angle-down rotate-icon"></i>

                    </a>

                    <div class="collapsible-body">

                        <ul>

                            <li>

                                <a href="../product/product-v1.html" class="waves-effect">Product V.1</a>

                            </li>

                            <li>

                                <a href="../product/product-v2.html" class="waves-effect">Product V.2</a>

                            </li>

                        </ul>

                    </div>

                </li>

                <li>

                    <a href="../contact/contact.html" class="collapsible-header waves-effect">

                        <i class="fas fa-envelope"></i> Contact</a>

                </li>

            </ul>

        </li>
        <!-- Side navigation links -->

        <div class="sidenav-bg mask-strong"></div>

    </ul>
    <!-- Sidebar navigation -->

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar white">

        <div class="container">

            <!-- SideNav slide-out button -->
            <div class="float-left mr-2">

                <a href="#" data-activates="slide-out" class="button-collapse">

                    <i class="fas fa-bars"></i>

                </a>

            </div>

            <a class="navbar-brand font-weight-bold" href="#">

                <strong>SHOP</strong>

            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
                    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>

            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent-4">

                <ul class="navbar-nav ml-auto">

                    <li class="nav-item ">

                        <a class="nav-link dark-grey-text font-weight-bold" href="<?=$this->url('application',['action'=>'cart'])?>">

                            <span class="badge danger-color"><?=$cartCount?></span>

                            <i class="fas fa-shopping-cart blue-text" aria-hidden="true"></i>

                            <span class="clearfix d-none d-sm-inline-block">Cart</span>
                            <span class="clearfix red-text d-none d-sm-inline-block">$<?=$totalPrice?></span>

                        </a>

                    </li>

                    <li class="nav-item ml-3">

                        <a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" href="#">

                            <i class="fas fa-cog blue-text"></i> Settings</a>

                    </li>

                    <li class="nav-item dropdown ml-3">

                        <a class="nav-link dropdown-toggle waves-effect waves-light dark-grey-text font-weight-bold"
                           id="navbarDropdownMenuLink-4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                            <i class="fas fa-user blue-text"></i> Profile </a>

                        <div class="dropdown-menu dropdown-menu-right dropdown-cyan" aria-labelledby="navbarDropdownMenuLink-4">

                            <a class="dropdown-item waves-effect waves-light" href="#">My account</a>

                            <a class="dropdown-item waves-effect waves-light" href="#">Log out</a>

                        </div>

                    </li>

                </ul>

            </div>

        </div>

    </nav>
    <!-- Navbar -->

</header>
<!-- Navigation -->

<!-- Main Container -->
<div class="container mt-5 pt-3">

    <!-- Section: Product detail -->
    <section id="content" class="pb-5">

        <?= $this->content ?>

    </section>

</div>
<!-- Main Container -->

<!-- Footer -->
<footer class="page-footer text-center text-md-left stylish-color-dark pt-0">

    <!-- Copyright -->
    <div class="footer-copyright py-3 text-center">

        <div class="container-fluid">

            © 2020 Copyright:

            <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> JARADI LLC  </a>

        </div>

    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->



<!-- SCRIPTS -->
<!-- Materialize core JavaScript -->
<script type="text/javascript" src="/mamaz/public/js/perfect-scrollbar.min.js"></script>

<!-- JQuery -->
<script type="text/javascript" src="/mamaz/public/js/jquery-3.4.1.min.js"></script>

<!-- Bootstrap tooltips -->
<script type="text/javascript" src="/mamaz/public/js/popper.min.js"></script>

<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="/mamaz/public/js/bootstrap.min.js"></script>

<!-- MDB core JavaScript -->
<script type="text/javascript" src="/mamaz/public/js/mdb.min.js"></script>

<script type="text/javascript">
    /* WOW.js init */
    new WOW().init();
    // SideNav Button Initialization

    $(".button-collapse").sideNav();
    // SideNav Scrollbar Initialization

    var sideNavScrollbar = document.querySelector('.custom-scrollbar');
    // Ps.initialize(sideNavScrollbar);
    const ps = new PerfectScrollbar(sideNavScrollbar);
    // Tooltips Initialization
    $(function () {

        $('[data-toggle="tooltip"]').tooltip()
    });
    // Material Select Initialization
    $(document).ready(function () {

        // $('.mdb-select').material_select();
    });

</script>

</body>

</html>
