<section class="section pt-4">

    <!-- Grid row -->
    <div class="row">

        <!-- Grid column -->
        <div class="col-lg-6 col-md-12 mb-3 pb-lg-2">

            <!-- Image -->
            <div class="view zoom z-depth-1">

                <img src="..\img\Mama_Zs_African_Supermarket_Restaurant_Oklahoma_City.OK.png"class="img-fluid" alt="sample image">

                <div class="mask rgba-white-light">

                    <div class="dark-grey-text d-flex align-items-center pt-4 ml-3 pl-3">

<!--                        <div>

                            <a><span class="badge badge-danger">bestseller</span></a>

                            <h2 class="card-title font-weight-bold pt-2"><strong>This is news title</strong></h2>

                            <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>

                            <a class="btn btn-danger btn-sm btn-rounded clearfix d-none d-md-inline-block waves-effect waves-light">Read more</a>

                        </div>-->

                    </div>

                </div>

            </div>
            <!-- Image -->

        </div>
        <!-- Grid column -->

    </div>
    <!-- Grid row -->

    <!-- Section small products -->
    <section>

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-12">

                <!-- Grid row -->
                <div class="row">

                    <!-- Grid column -->
                    <div class="col-lg-6 col-md-6 mb-4">
                        <!-- Card -->
                        <div class="card card-cascade narrower">

                            <!-- Card image -->
                            <div class="view view-cascade overlay">
                                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/8-col/img (5).jpg" alt="Card image cap">
                                <a>
                                    <div class="mask rgba-white-slight waves-effect waves-light"></div>
                                </a>
                            </div>

                            <!-- Card content -->
                            <div class="card-body card-body-cascade">

                                <!-- Label -->
                                <h5 class="pink-text pb-2 pt-1"><i class="fas fa-utensils"></i> Culinary</h5>
                                <!-- Title -->
                                <h4 class="font-weight-bold card-title">Menu</h4>
                                <!-- Text -->
                                <p class="card-text">Here to view our menu.</p>
                                <!-- Button -->
                                <a class="btn btn-unique waves-effect waves-light" href="application/menu">Menu</a>

                            </div>

                            <!-- Card footer -->
<!--                            <div class="card-footer text-muted text-center">
                                2 days ago
                            </div>-->

                        </div>
                        <!-- Card -->
                    </div>
                    <div class="col-lg-6 col-md-6 mb-4">
                        <div class="card card-cascade narrower">

                            <!-- Card image -->
                            <div class="view view-cascade overlay">
                                <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Horizontal/Food/8-col/img (5).jpg" alt="Card image cap">
                                <a>
                                    <div class="mask rgba-white-slight waves-effect waves-light"></div>
                                </a>
                            </div>

                            <!-- Card content -->
                            <div class="card-body card-body-cascade">

                                <!-- Label -->
                                <h5 class="pink-text pb-2 pt-1"><i class="fas fa-utensils"></i> Culinary</h5>
                                <!-- Title -->
                                <h4 class="font-weight-bold card-title">Order Status</h4>
                                <!-- Text -->
                                <p class="card-text">Go here to check your order status.</p>
                                <!-- Button -->
                                <a class="btn btn-unique waves-effect waves-light" href="application/orderstatus">Status</a>

                            </div>

                            <!-- Card footer -->
<!--                            <div class="card-footer text-muted text-center">
                                2 days ago
                            </div>-->

                        </div>
                    </div>
                    <!-- Grid column -->

                </div>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </section>
    <!-- Section small products -->s