<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">MamaZ</span></h1>
    <div class="row align-self-auto">
        <div class="col-md-6">
<!--            <div class="buttonPrimary">-->
                <a class="btn btn-lg btn-success" href="application/menu" >
                View Menu
                </a>
<!--            </div>-->
        </div>
        <div class="col-md-6">
<!--            <div class="buttonPrimary">-->
            <a class="btn btn-success btn-lg" href="application/orderstatus">
                Order Status
            </a>
<!--            </div>-->
        </div>
    </div>
</div>