<?php
?>

<div class="container">
    <div class="row">
        <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
            <div class="px-2">
                <!--                                 Default form login-->
                <form method="post" class="justify-content-center"action="<?=$this->url('application',['action'=>'createOrder'])?>">
                    <p class="h4 mb-4">Start Order</p>
                    <!--                                     Email-->
                    <input type="text" class="form-control mb-4" placeholder="Order name" name="username" >
                    <!--                                     Sign in button-->
                    <button class="btn btn-info btn-block my-4" type="submit" href="">Start order</button>
                    <!--                                     Social login-->
                </form>
            </div>
        </div>
    </div>
</div>

