<?php
/**
 * @var \Application\Model\Entity\MenuItem $menuItem
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

use Application\Model\Entity\Condiment;

?>

<section id="productDetails" class="pb-5" xmlns="http://www.w3.org/1999/html">
<form name="orderitem" method="post" action="<?=$this->url('application', [ 'action' => 'addToCart', 'id' => $menuItem->getId()])?>">
    <!-- News card -->
    <div class="card mt-5 hoverable">

        <div class="row mt-5">

            <div class="col-lg-6">

                <!-- Carousel Wrapper -->
                <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">

                    <!-- Slides -->
                    <div class="carousel-inner text-center text-md-left" role="listbox">

                        <div class="carousel-item active">

                            <img src="<?=$menuItem->getImageMain()?>" alt="First slide"
                                 class="img-fluid">

                        </div>

                        <div class="carousel-item">

                            <img src="<?=$menuItem->getImageMain()?>" alt="Second slide"
                                 class="img-fluid">

                        </div>

                        <div class="carousel-item">

                            <img src="<?=$menuItem->getImageMain()?>" alt="Third slide"
                                 class="img-fluid">

                        </div>

                    </div>
                    <!-- Slides -->

                    <!-- Thumbnails -->
                    <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">

                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>

                        <span class="sr-only">Previous</span>

                    </a>

                    <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">

                        <span class="carousel-control-next-icon" aria-hidden="true"></span>

                        <span class="sr-only">Next</span>

                    </a>
                    <!-- Thumbnails -->

                </div>
                <!-- Carousel Wrapper -->

            </div>

            <div class="col-lg-5 mr-3 text-center text-md-left">

                <h2
                    class="h2-responsive text-center text-md-left product-name font-weight-bold dark-grey-text mb-1 ml-xl-0 ml-4">

                    <strong><?=$menuItem->getItemName()?></strong>

                </h2>

<!--                <span class="badge badge-danger product mb-4 ml-xl-0 ml-4">bestseller</span>-->

                <h3 class="h3-responsive text-center text-md-left mb-5 ml-xl-0 ml-4">

              <span class="red-text font-weight-bold">

                <strong>$<?=$menuItem->getPrice()?></strong>

              </span>

                </h3>

                <!-- Accordion wrapper -->
                <div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">

                    <!-- Accordion card -->
                    <div class="card">

                        <!-- Card header -->
                        <div class="card-header" role="tab" id="headingOne1">

                            <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="true"
                               aria-controls="collapseOne1">

                                <h5 class="mb-0">

                                    Description

                                    <i class="fas fa-angle-down rotate-icon"></i>

                                </h5>

                            </a>

                        </div>

                        <!-- Card body -->
                        <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1"
                             data-parent="#accordionEx">

                            <div class="card-body">

                                <?=$menuItem->getItemDesc()?>

                            </div>

                        </div>

                    </div>
                    <!-- Accordion card -->

                    <!-- Accordion card -->
                    <div class="card">

                        <!-- Card header -->
                        <div class="card-header" role="tab" id="headingTwo2">

                            <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseTwo2"
                               aria-expanded="false" aria-controls="collapseTwo2">

                                <h5 class="mb-0">

                                    Condiments

                                    <i class="fas fa-angle-down rotate-icon"></i>

                                </h5>

                            </a>

                        </div>

                        <!-- Card body -->
                        <div id="collapseTwo2" class="collapse" role="tabpanel" aria-labelledby="headingTwo2"
                             data-parent="#accordionEx">

                            <div class="card-body">

                                <p class="grey-text">Choose your Condiments</p>

                                <div class="row text-center text-md-left">
                                    <section>
                                        <table id="condiments" class="table" width="100%">
                                            <thead>
                                            <tr>
                                                <th class="th-sm">Condiment</th>
                                                <th class="th-sm">Quantity</th>
                                            </tr>
                                            </thead>
                                            <tbody>
<?php
/** @var Condiment $condiment */
foreach($menuItem->getCondiments() as $condiment):
    ?>
<tr>
        <td class="tex center text-md-left"><?=$condiment->getItemName()?></td>

    <td class="text-center text-md-left">

                <span type="number" id="condiment-qty" class="qty condiment-<?=$condiment->getId()?>">0</span>
        <input type="hidden"  name="condiments[<?=$condiment->getId()?>]"  id="condiments[<?=$condiment->getId()?>]" value="0">

        <div class="btn-group radio-group ml-2" data-toggle="buttons">

<!--                <input class="quantity" type="number" name="options" min="0" value="0" id="option1" maxlength="1" size="1">-->

            <button class="btn btn-sm btn-primary btn-rounded waves-effect waves-light minus-btn" type="button" id="<?=$condiment->getId()?>" >

                <input type="radio" name="options" class=""  id="option1">—

            </button>

            <button class="btn btn-sm btn-primary btn-rounded waves-effect waves-light plus-btn" type="button"  id="<?=$condiment->getId()?>">

                <input type="radio" name="options"  class="" id="option2">+

            </button>

        </div>

    </td>
</tr>

<?php
endforeach;?>
<?php
echo $this->inlineScript()->setFile('/public/js/mamaz/orderitem.js');
?>
                                    </tbody>
                                    </table>
                                    </section>

                                </div>

                            </div>

                        </div>

                    </div>
                    <!-- Accordion card -->

                    <!-- Accordion card -->
                    <!-- Accordion card -->

                </div>
                <!-- Accordion wrapper -->

                <!-- Add to Cart -->
                <section class="color">

                    <div class="mt-5">


                        <div class="row mt-3 mb-4">

                            <div class="col-md-12 text-center text-md-left text-md-right">

                                <button class="btn btn-primary btn-rounded" type="submit">

                                    <i class="fas fa-cart-plus mr-2" aria-hidden="true"></i> Add to cart</button>

                            </div>

                        </div>

                    </div>

                </section>
                <!-- Add to Cart -->

            </div>

        </div>

    </div>
</form>
</section>
